# In Class Notebook, Week 06

You can click on the GitHub URL of this notebook to access the file in near-real time: https://github.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2025/blob/master/week06/inClass_week06.ipynb 

In [1]:
import ipywidgets

In [4]:
islider = ipywidgets.IntSlider(min=0, max=10, step=1, orientation='vertical')
#islider

In [5]:
cp = ipywidgets.ColorPicker()
#cp

In [6]:
ipywidgets.link( (cp, 'value'), (islider.style, 'handle_color'))

In [7]:
ipywidgets.HBox([cp, islider])

In [8]:
class MyObject():
    name = 'unnamed'
    age = 0

In [9]:
my_obj = MyObject()

In [10]:
my_obj.name, my_obj.age

('unnamed', 0)

In [12]:
my_obj.name = 'Bob'
my_obj.age = 47

In [13]:
print('Hello, my name is', my_obj.name, 'and I am', my_obj.age, 'years old.')

Hello, my name is Bob and I am 47 years old.


In [14]:
# class MyObject():
#     name = 'unnamed'
#     age = 0

import traitlets

In [15]:
class MyTraitletObject(traitlets.HasTraits):
    name = traitlets.Unicode('unnamed') # string
    age = traitlets.Int(0) # integer

In [16]:
my_t_obj = MyTraitletObject()

In [17]:
my_t_obj.name, my_t_obj.age

('unnamed', 0)

In [18]:
def name_changed(change): # event? change?
    print(change)

my_t_obj.observe(name_changed, ['name'])

In [19]:
my_t_obj.name = 'Linda'

{'name': 'name', 'old': 'unnamed', 'new': 'Linda', 'owner': <__main__.MyTraitletObject object at 0x106df4b20>, 'type': 'change'}


In [22]:
def name_changed2(change): # event? change?
    #print(change)
    print('Hello, my name is', change['new'], 'and I am', change['owner'].age, 'years old.')

my_t_obj.observe(name_changed2, ['name'])

In [24]:
my_t_obj.name = 'Linda'

{'name': 'name', 'old': 'Bob', 'new': 'Linda', 'owner': <__main__.MyTraitletObject object at 0x106df4b20>, 'type': 'change'}
Hello, my name is Linda and I am 0 years old.
Hello, my name is Linda and I am 0 years old.


In [25]:
my_t_obj.unobserve(name_changed2, ['name'])

In [26]:
my_t_obj = MyTraitletObject()

def name_changed(change): 
    print('Hello, my name is', change['new'], 'and I am', change['owner'].age, 'years old.')

my_t_obj.observe(name_changed, ['name'])

In [27]:
my_t_obj.name = 'Linda'

Hello, my name is Linda and I am 0 years old.


In [28]:
my_t_obj.name = 'Linda'

In [29]:
def age_changed(change):
    print('Hello, my name is', change['owner'].name, 'and I am', change['new'], 'years old.')

my_t_obj.observe(age_changed, ['age'])

In [30]:
my_t_obj.age = 45

Hello, my name is Linda and I am 45 years old.


In [31]:
my_t_obj.name = 'Bob'
my_t_obj.age = 47

Hello, my name is Bob and I am 45 years old.
Hello, my name is Bob and I am 47 years old.


## Intro to bqplot

In [32]:
import bqplot

In [33]:
import numpy as np

In [34]:
# 1. Data
x = np.arange(100)
y = np.random.random(100)

In [37]:
#y

In [40]:
# 2. Scales
#bqplot.LinearScale?
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [42]:
# 3. Axis
#bqplot.Axis?
ax_x = bqplot.Axis(scale=x_sc, label='X Values')
ax_y = bqplot.Axis(scale=y_sc, label='Y Values', orientation='vertical')

In [44]:
# 4. Marks (sometimes we do axis before/after)
#bqplot.Lines?
lines = bqplot.Lines(x=x, y=y, scales= {'x':x_sc, 'y':y_sc})

In [45]:
# 5. interactivity

In [46]:
# 6. put everything together into a figure
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y])

In [47]:
fig

Figure(axes=[Axis(label='X Values', scale=LinearScale(), side='bottom'), Axis(label='Y Values', orientation='v…

In [48]:
# 1. Data
x = np.arange(100)
y = np.random.random(100)

# 2. Scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. Axis
ax_x = bqplot.Axis(scale=x_sc, label='X Values')
ax_y = bqplot.Axis(scale=y_sc, label='Y Values', orientation='vertical')

# 4. Marks (sometimes we do axis before/after)
lines = bqplot.Lines(x=x, y=y, scales= {'x':x_sc, 'y':y_sc})

# 5. interactivity

# 6. put everything together into a figure
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y])

fig

Figure(axes=[Axis(label='X Values', scale=LinearScale()), Axis(label='Y Values', orientation='vertical', scale…

In [49]:
bqplot.interacts.PanZoom?

Init signature: bqplot.interacts.PanZoom(*args: 't.Any', **kwargs: 't.Any') -> 't.Any'
Docstring:     
An interaction to pan and zoom wrt scales.

Attributes
----------
allow_pan: bool (default: True)
    Toggle the ability to pan.
allow_zoom: bool (default: True)
    Toggle the ability to zoom.
scales: Dictionary of lists of Scales (default: {})
    Dictionary with keys such as 'x' and 'y' and values being the scales in
    the corresponding direction (dimensions) which should be panned or
    zoomed.
Init docstring: Public constructor
File:           /opt/anaconda3/envs/DataViz/lib/python3.10/site-packages/bqplot/interacts.py
Type:           MetaHasTraits
Subclasses:     

In [50]:
# 1. Data
x = np.arange(100)
y = np.random.random(100)

# 2. Scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. Axis
ax_x = bqplot.Axis(scale=x_sc, label='X Values')
ax_y = bqplot.Axis(scale=y_sc, label='Y Values', orientation='vertical')

# 4. Marks (sometimes we do axis before/after)
lines = bqplot.Lines(x=x, y=y, scales= {'x':x_sc, 'y':y_sc})

# 5. interactivity
pz = bqplot.interacts.PanZoom(scales={'x':[x_sc], 'y':[y_sc]})

# 6. put everything together into a figure
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y], interaction=pz)

fig

Figure(axes=[Axis(label='X Values', scale=LinearScale()), Axis(label='Y Values', orientation='vertical', scale…

In [54]:
#bqplot.Scatter?

In [58]:
# 1. Data
x = np.random.random(100)
y = np.random.random(100)

# 2. Scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. Axis
ax_x = bqplot.Axis(scale=x_sc, label='X Values')
ax_y = bqplot.Axis(scale=y_sc, label='Y Values', orientation='vertical')

# 4. Marks (sometimes we do axis before/after)
scatters = bqplot.Scatter(x=x, y=y, scales= {'x':x_sc, 'y':y_sc})

# 5. interactivity
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks=[scatters])

# 6. put everything together into a figure
fig = bqplot.Figure(marks=[scatters], axes=[ax_x, ax_y], interaction=selector)

fig

Figure(axes=[Axis(label='X Values', scale=LinearScale()), Axis(label='Y Values', orientation='vertical', scale…

In [60]:
selector.selected

array([0.06176093, 0.50337321])

In [61]:
scatters.selected_style = {'fill':'red', 'stroke':'yellow'}

## 2D heatmap (random data)

In [65]:
# 1. data
data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale()

# 3. axis

# 4. mark
heatmap = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. interactivity

# 6. all together into a figure
fig = bqplot.Figure(marks=[heatmap])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.44963…

In [66]:
# 1. data
data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')

# 3. axis

# 4. mark
heatmap = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. interactivity

# 6. all together into a figure
fig = bqplot.Figure(marks=[heatmap])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.95190…

In [69]:
# 1. data
data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # try changing to LinearScale and see what happens
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heatmap = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                            interactions={'click':'select'}, 
                            anchor_style={'fill':'magenta'})

# 5. interactivity

# 6. all together into a figure
fig = bqplot.Figure(marks=[heatmap], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(label='C…

In [72]:
heatmap.selected

array([[0, 6]])

In [73]:
import ipywidgets

In [74]:
myLabel = ipywidgets.Label()

In [75]:
myLabel.value

''

In [80]:
# 1. data
data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # try changing to LinearScale and see what happens
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heatmap = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                            interactions={'click':'select'}, 
                            anchor_style={'fill':'magenta'})

# 5. interactivity
def on_selected(change):
    #print(change)
    if len(change['owner'].selected) == 1: # only one single selection at a time
        #print(change['owner'].selected)
        i,j = change['owner'].selected[0] # check if i,j should be j,i by click on some values
        myLabel.value = 'Data value = ' + str(data[i,j])

heatmap.observe(on_selected, 'selected')

# 6. all together into a figure
fig = bqplot.Figure(marks=[heatmap], axes=[col_ax, x_ax, y_ax])
#fig
dashboard = ipywidgets.VBox([myLabel,fig])
dashboard

## Adding complexity -- 3D heatmap with random data

In [81]:
data3d = np.random.random((10,10,20))

In [83]:
data3d.shape

(10, 10, 20)

In [93]:
# 1. data

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # try changing to LinearScale and see what happens
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heatmap = bqplot.GridHeatMap(color=np.sum(data3d,axis=2), # changed this for 3d data
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                            interactions={'click':'select'}, 
                            anchor_style={'fill':'magenta'})

# 5. interactivity
myLabel = ipywidgets.Label()
def on_selected(change):
    if len(change['owner'].selected) == 1: # only one single selection at a time
        i,j = change['owner'].selected[0] # check if i,j should be j,i by click on some values
        myLabel.value = 'Data value (sum) = ' + str(np.sum(data3d[i,j,:])) 

heatmap.observe(on_selected, 'selected')

# 6. all together into a figure
fig = bqplot.Figure(marks=[heatmap], axes=[col_ax, x_ax, y_ax])
#fig
dashboard = ipywidgets.VBox([myLabel,fig])
dashboard

In [101]:
heatmap.selected

array([[3, 6]])

In [102]:
i,j = heatmap.selected[0]
i,j

(3, 6)

In [103]:
data3d[i,j,:] # 1. data for histogram

array([0.81046118, 0.88686981, 0.43048115, 0.57824139, 0.92038466,
       0.27988933, 0.20288431, 0.50571256, 0.27478091, 0.94567342,
       0.7719918 , 0.84712712, 0.07327933, 0.82495357, 0.5537984 ,
       0.21303857, 0.53461058, 0.54041031, 0.90074141, 0.78401021])

In [104]:
# 2. scales
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

# 3. axes for histogram
x_axh = bqplot.Axis(scale=x_sch, label='Value for 3rd axis')
y_axh = bqplot.Axis(scale=y_sch, label='Frequency', orientation='vertical')

In [105]:
# 4. mark
#bqplot.Hist?
hist = bqplot.Hist(sample=data3d[i,j,:], scales={'sample':x_sch, 'count':y_sch}, bins=5)

In [106]:
# 5. interactivity for histogram (number of bins change?)

# 6. figure
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value for 3rd axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', ori…

In [107]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [108]:
hist.sample

array([0.81046118, 0.88686981, 0.43048115, 0.57824139, 0.92038466,
       0.27988933, 0.20288431, 0.50571256, 0.27478091, 0.94567342,
       0.7719918 , 0.84712712, 0.07327933, 0.82495357, 0.5537984 ,
       0.21303857, 0.53461058, 0.54041031, 0.90074141, 0.78401021])

In [111]:
# 1. data

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # try changing to LinearScale and see what happens
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heatmap = bqplot.GridHeatMap(color=np.sum(data3d,axis=2), # changed this for 3d data
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                            interactions={'click':'select'}, 
                            anchor_style={'fill':'magenta'})

# 5. interactivity
myLabel = ipywidgets.Label()
def on_selected(change):
    if len(change['owner'].selected) == 1: # only one single selection at a time
        i,j = change['owner'].selected[0] # check if i,j should be j,i by click on some values
        myLabel.value = 'Data value (sum) = ' + str(np.sum(data3d[i,j,:])) # updating the value attribute of myLabel
        hist.sample = data3d[i,j,:] # update the sample attribute of hist 

heatmap.observe(on_selected, 'selected')

# 6. all together into a figure
fig = bqplot.Figure(marks=[heatmap], axes=[col_ax, x_ax, y_ax])
#fig
#dashboard = ipywidgets.VBox([myLabel,fig])
figures = ipywidgets.HBox([fig, figh])
dashboard = ipywidgets.VBox([myLabel, figures])
fig.layout.min_width = '400px'
figh.layout.min_width = '400px'
dashboard